### ISSUE TITLE
Scores no longer updating in radarr (sonarr untested)

### ISSUE THREAD

**Issue by Brandoskey** [recyclarr/recyclarr#160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When recyclarr runs using the latest release 4.1.1 it does not update scores when manually set in the yaml nor does it update scores that are changed from the guides default in radarr

I went back to version 4.0 of the dockerhub container and it works as expected

reset_unmatched_scores: seems to work as expected

### Expected Behavior

Scores should update based on the guide values or the values manually set in the yaml

### Steps To Reproduce

Set a manual score in the yaml or update a score in radarr

run recyclarr

not that scores do not update

### Environment & Versions

```bash
- Operating System: ubuntu
- Architecture:
- Recyclarr Version: 4.1.1
- Recyclarr Build:
- Sonarr Version:
- Radarr Version: 4.3.2.6857
```

### Recyclarr Log File(s)

[trash_2023-01-06_12-01-55.log](https://github.com/recyclarr/recyclarr/files/10362288/trash_2023-01-06_12-01-55.log)

### Configuration YAML

```YAML
radarr:
  movies:
    # Set the URL/API Key to your actual instance
    base_url: 
    api_key: 

    # Which quality definition in the guide to sync to Radarr. Only choice right now is 'movie'
    #quality_definition:
    #  type: movie

    # Set to 'true' to automatically remove custom formats from Radarr when they are removed from
    # the guide or your configuration. This will NEVER delete custom formats you manually created!
    delete_old_custom_formats: true

    custom_formats:
      # A list of custom formats to sync to Radarr.
      # Use `recyclarr radarr --list-custom-formats` for values you can put here.
      # https://trash-guides.info/Radarr/Radarr-collection-of-custom-formats/
      - trash_ids:
          - ed38b889b31be83fda192888e2286d83 # BR-DISK
          - 90cedc1fea7ea5d11298bebd3d1d3223 # EVO (no WEBDL)
          - 90a6f9a284dff5103f6346090e6280c8 # LQ
          - dc98083864ea246d05a42df0d05f81cc # x265 (720/1080p)
          - b8cd450cbfa689c0259a01d9e29ba3d6 # 3D
        quality_profiles: 
          - name: Ultra-HD - x265
            #score: -1000
            #reset_unmatched_scores: false
      - trash_ids:
          - 4a3b087eea2ce012fcc1ce319259a3be # ANIME DUAL AUDIO
          - 9170d55c319f4fe40da8711ba9d8050d # x265 (4k)
          - eecf3a857724171f968a66cb5719e152 # IMAX

        # Uncomment the below properties to specify one or more quality profiles that should be
        # updated with scores from the guide for each custom format. Without this, custom formats
        # are synced to Radarr but no scores are set in any quality profiles.
        #quality_profiles:
        #  - name: Quality Profile 1
        #  - name: Quality Profile 2
        #    score: -9999 # Optional score to assign to all CFs. Overrides scores in the guide.
        #    reset_unmatched_scores: true # Optionally set other scores to 0 if they are not listed in 'names' above.
      - trash_ids:
          - 496f355514737f7d83bf7aa4d24f8169 #TrueHD ATMOS
          - 2f22d89048b01681dde8afe203bf2e95 #DTS X
        quality_profiles:
          - name: SD
```

**Comment by rcdailey** [comment]
Should be fixed in v4.1.2

**Comment by Brandoskey** [comment]
Thanks, I updated to 4.1.2 via dockerhub and the problem persists. Just to make sure I switched back to 4.0 and it works as expected.

I basically created a test profile on radarr, added it to the yaml and ran 4.1.2 and it didn't update scores. Ran the same yaml through 4.0 and it updated scores as expected.

**Comment by rcdailey** [comment]
Could you zip up your `cache` directory and attach it here?

**Comment by Brandoskey** [comment]
[cache.zip](https://github.com/recyclarr/recyclarr/files/10366586/cache.zip)

Here you go

**Comment by rcdailey** [comment]
@Brandoskey I have a fix on `master` that I'd like you to test. Please use the latest Docker image using the `edge` tag, or if you use a manual install you can grab an adhoc build for your platform here: https://github.com/recyclarr/recyclarr/actions/runs/3863204275

Let me know if your issue is addressed.

**Comment by Brandoskey** [comment]
Scores are now syncing

I manually edited some scores in a test profile in radarr and running recyclarr switched them back to the guide scores as expected

I also used "score:" to manually set a score on the same profile for various trash-id's and that also updated the scores as expected.

The fix works on my end, thanks again for the great software!
